### ISSUE TITLE
这个是哪里出了问题,

### ISSUE THREAD

**Issue by gaidehaha** [M1r0ku/YuqueExport#7]
Traceback (most recent call last):
  File "D:\Userfile\下载\YuqueExport-master\YuqueExport-master\YuqueExport.py", line 219, in <module>
    asyncio.run(main())
  File "D:\Program Files\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\Program Files\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Userfile\下载\YuqueExport-master\YuqueExport-master\YuqueExport.py", line 183, in main
    await download_md(repo_id, repo_name, doc_id, doc_title)
  File "D:\Userfile\下载\YuqueExport-master\YuqueExport-master\YuqueExport.py", line 95, in download_md
    f.write(record_doc_output)
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f4c6' in position 3: illegal multibyte sequence
PS D:\Userfile\下载\YuqueExport-master\YuqueExport-master>

**Comment by M1r0ku** [comment]
应该是文章里包含了例如emoji等的特殊字符导致无法解析，可以把字符删掉再尝试导出

**Comment by woshitieren** [comment]
这个估计是没有输入token
